"""empty message

Revision ID: 3f5d7e9f44b0
Revises: 
Create Date: 2020-02-29 21:04:04.204058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5d7e9f44b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datarecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employerId', sa.Integer(), nullable=True),
    sa.Column('courseNumber', sa.Integer(), nullable=True),
    sa.Column('hasRecu', sa.String(length=10), nullable=True),
    sa.Column('descriptionName', sa.String(length=60), nullable=True),
    sa.Column('dateAtten', sa.String(length=30), nullable=True),
    sa.Column('ceCo', sa.String(length=12), nullable=True),
    sa.Column('trainingGroup', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('hours', sa.String(length=3), nullable=True),
    sa.Column('days', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('sta', sa.String(length=1), nullable=True),
    sa.Column('anp', sa.Integer(), nullable=True),
    sa.Column('insIni', sa.String(length=3), nullable=True),
    sa.Column('recurrent', sa.String(length=1), nullable=True),
    sa.Column('oneYearExpire', sa.String(length=30), nullable=True),
    sa.Column('twoYearExpire', sa.String(length=30), nullable=True),
    sa.Column('threeYearExpire', sa.String(length=30), nullable=True),
    sa.Column('fourYearExpire', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('avatar', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('datarecord')
    # ### end Alembic commands ###
